### ISSUE TITLE
Small Suggestions

### ISSUE THREAD

**Issue by ghost** [samipak458/Take-Online-Notes#1]
I generally like the idea behind this app, and I think it's well executed. However, I still noticed five minor (potential) flaws:

**1. Fonts** 
I'm unsure of whether this was done on purpose or not, but the font of the input element isn't the same as the font later used to display the saved notes. 

**2. Dark Mode**
The contrast is still too strong in my opinion. I suggest lowering the colour intensity for dark mode. I also suggest you store the mode choice (light or dark) of the user using 'localstorage'. 

**3. Search Bar**
It looks and works well, but I'd be nice if I could interact with it by clicking on it further to right. As of now, you have to click relatively close to the placeholder to do so. 

**4. Menu**
If you watch closely, then you'll notice a thin, white line that sticks to the menu just below it. You may have done this on purpose, but I'm convinced that it'd look "cleaner" if it was removed. Like my other suggestions, this is just an opinion - feel free to disagree. 

**5. Copy-Paste**
Currently, if you try to paste text into the text input element that's longer than 200 characters, then nothing happens. I suggest that you choose between adding some kind of popup to let the user know, or to take as many characters as possible and add them to the input. 

Overall though, well done! I'm not very familiar with React, but it's great to see you play around with it. Keep learning and let me know if you found this feedback helpful. Once again, none of it is meant offensively, and feel free to explain anything I've misinterpreted!

**Comment by samipak458** [comment]
@gabscholler Thank you so much for the detailed suggestions, I will definitely look into it. 
Mainly my focus is to help the beginners in understanding the concepts of React JS by implementing it.
