### ISSUE TITLE
bug: Wrong item getting deleted

### ISSUE THREAD

**Issue by reetsrivastava** [samipak458/Take-Online-Notes#10]
@samipak458 Seems like on deleting an item from the notes it is deleting the first element of the collection rather than deleting the exact item. 
I want to fix this bug. Kindly assign me the issue under hacktoberfest and will raise the PR. Thanks.

**Comment by samipak458** [comment]
Thanks for creating an issue. Go ahead and fix it @reetsrivastava

**Comment by reetsrivastava** [comment]
@samipak458 Raised PR for the fix https://github.com/samipak458/Take-Online-Notes/pull/14. Please check.
