### ISSUE TITLE
Enhancement : UI Enhancement

### ISSUE THREAD

**Issue by reetsrivastava** [samipak458/Take-Online-Notes#11]
@samipak458 Would like to enhance 

- Notes Under different section of screen, apart from take a note.
- Change the look of the toggle button

Would be great if you assign this to me under hacktoberfest.

**Comment by samipak458** [comment]
Thanks for creating an issue. Go ahead and fix it @reetsrivastava

**Comment by reetsrivastava** [comment]
@samipak458 Have raised the PR for this https://github.com/samipak458/Take-Online-Notes/pull/13. Please check.
