### ISSUE TITLE
Migrate storage to redux

### ISSUE THREAD

**Issue by rajdip-b** [samipak458/Take-Online-Notes#15]
## Features to add:
- Navigation between saved notes
- Save/Edit/Delete notes in local storage
- Download notes locally onto pc.

Can I be assigned this under hacktoberfest2022?

**Comment by samipak458** [comment]
Sure, Go ahead @rajdip-b 
**Note: don't forget to sync the fork.**

**Comment by rajdip-b** [comment]
Hey @samipak458, I somehow overlooked that saving and deletion is already present. I want to convert the storage into redux if that is ok. Ill close this issue if its not doable.

**Comment by samipak458** [comment]
No need to use redux. You can add downloading functionality @rajdip-b .

**Comment by rajdip-b** [comment]
Okay cool

**Comment by samipak458** [comment]
@rajdip-b updates?

**Comment by samipak458** [comment]
@rajdip-b ?
