### ISSUE TITLE
Refactor to TailwindCSS

### ISSUE THREAD

**Issue by rajdip-b** [samipak458/Take-Online-Notes#16]
## Description:
I want to refactor this project's styling to tailwind css.

 Can I be assigned this issue under hacktoberfest2022?

**Comment by samipak458** [comment]
Go ahead @rajdip-b 
Don't delete the current CSS, you can comment out or make it separate file. Do proper comments on each part of code.

**Comment by rajdip-b** [comment]
> Go ahead @rajdip-b Don't delete the current CSS, you can comment out or make it separate file. Do proper comments on each part of code.

Okay so do I create a folder in src named src_old and put the files in there??

**Comment by samipak458** [comment]
Yes, 
Also do proper commenting in code.
