### ISSUE TITLE
Update toggle theme button

### ISSUE THREAD

**Issue by rajdip-b** [samipak458/Take-Online-Notes#17]
## Description
I want to add a toggle button that would look like [this](https://img.freepik.com/premium-vector/daymode-nightmode-switch-button-light-dark-theme_399089-668.jpg?w=2000)

Can I be assigned this issue under hacktoberfest?

**Comment by samipak458** [comment]
Go ahead @rajdip-b

**Comment by samipak458** [comment]
Does this issue resolved @rajdip-b ?

**Comment by rajdip-b** [comment]
> Does this issue resolved @rajdip-b ?

Sorry I had some unfinished business. I am starting it today. :/
