### ISSUE TITLE
Toggle mode not working properly

### ISSUE THREAD

**Issue by Alok5102R** [samipak458/Take-Online-Notes#19]
@samipak458  toggle mode isn't optimized properly. I would like to work upon this issue.

https://user-images.githubusercontent.com/56478877/197404287-1acbabe0-58d4-425c-9f74-604840549261.mp4

**Comment by samipak458** [comment]
Go ahead @Alok5102R and fix it

**Comment by Alok5102R** [comment]
@samipak458 have a look at [PR #21

**Comment by Alok5102R** [comment]
@samipak458 have a look at PR #21

**Comment by samipak458** [comment]
It is closed @Alok5102R

**Comment by Alok5102R** [comment]
@samipak458 Look at PR #21 
need to close previous pr due to removal of files from main.
